services:
  app:
    image: ghcr.io/excoffierleonard/transcriber
    container_name: transcriber-app
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    environment:
      MODEL_IDLE_TIMEOUT: ${MODEL_IDLE_TIMEOUT:-300}
    ports:
      - "${TRANSCRIBER_APP_PORT:-8080}:8080"
    networks:
      - transcriber
    # Enables GPU support
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all

networks:
  transcriber:
    name: transcriber
