services:
  app:
    image: ghcr.io/excoffierleonard/transcriber:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      MODEL_IDLE_TIMEOUT: ${MODEL_IDLE_TIMEOUT:-300}
      ENABLE_FRONTEND: ${ENABLE_FRONTEND:-false}
    ports:
      - "${TRANSCRIBER_APP_PORT:-8080}:8080"
    # Enables GPU support
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
